// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package wire

// パケット内のゲームの現状態を示す情報の構造体.
type Info struct {
	// 自分のエージェントの名前.
	Agent string `json:"agent"`

	// 襲撃の投票結果 (エージェントの役職が人狼かつ襲撃投票結果が公開されている場合のみ).
	AttackVoteList []Vote `json:"attack_vote_list,omitempty"`

	// 昨夜の襲撃結果 (エージェントが襲撃された場合のみ).
	AttackedAgent *string `json:"attacked_agent,omitempty"`

	// 現在の日数.
	Day int `json:"day"`

	// 占い師の結果 (エージェントの役職が占い師であるかつ占い結果が設定されている場合のみ).
	DivineResult *Judge `json:"divine_result,omitempty"`

	// 昨日の追放結果 (エージェントが追放された場合のみ).
	ExecutedAgent *string `json:"executed_agent,omitempty"`

	// ゲームの識別子.
	GameID string `json:"game_id"`

	// 霊媒師の結果 (エージェントの役職が霊媒師であるかつ霊媒結果が設定されている場合のみ).
	MediumResult *Judge `json:"medium_result,omitempty"`

	// 自分のエージェントのプロフィール. (リクエストの種類が INITIALIZE の場合のみ). 設定されない場合は None.
	Profile *string `json:"profile,omitempty"`

	// 残りのトークもしくは囁きリクエストを受信する可能性のある最大の回数. (リクエストの種類が TALK | WHISPER の場合のみ).
	RemainCount *int `json:"remain_count,omitempty"`

	// 残りのトークもしくは囁きリクエストで消費することのできる文字数. 最低文字数を除く. (リクエストの種類が TALK | WHISPER の場合のみ).
	// 制限がない場合は None.
	RemainLength *int `json:"remain_length,omitempty"`

	// 残りのトークもしくは囁きリクエストでスキップすることのできる回数. (リクエストの種類が TALK | WHISPER の場合のみ).
	RemainSkip *int `json:"remain_skip,omitempty"`

	// 各エージェントの役職を示すマップ (自分以外のエージェントの役職は見えません).
	RoleMap map[string]Role `json:"role_map"`

	// 各エージェントの生存状態を示すマップ.
	StatusMap map[string]Status `json:"status_map"`

	// 投票の結果 (投票結果が公開されている場合のみ).
	VoteList []Vote `json:"vote_list,omitempty"`
}

// 占い結果や霊媒結果などの判定結果を示す情報の構造体.
type Judge struct {
	// 判定を出したエージェントの名前.
	Agent string `json:"agent"`

	// 判定が出た日数.
	Day int `json:"day"`

	// 判定結果.
	Result Species `json:"result"`

	// 判定の対象となったエージェントの名前.
	Target string `json:"target"`
}

// パケットの構造体.
type Packet struct {
	// ゲームの現状態を示す情報.
	Info *Info `json:"info,omitempty"`

	// グループチャット方式でブロードキャストされた新しいトーク. (リクエストの種類が TALK_BROADCAST の場合のみ).
	NewTalk *Talk `json:"new_talk,omitempty"`

	// グループチャット方式でブロードキャストされた新しい囁き. (リクエストの種類が WHISPER_BROADCAST の場合のみ).
	NewWhisper *Talk `json:"new_whisper,omitempty"`

	// リクエストの種類.
	Request Request `json:"request"`

	// ゲームの設定情報.
	Setting *Setting `json:"setting,omitempty"`

	// トークの履歴を示す情報.
	TalkHistory *PacketTalkHistory `json:"talk_history,omitempty"`

	// 囁きの履歴を示す情報.
	WhisperHistory *PacketWhisperHistory `json:"whisper_history,omitempty"`
}

// トークの履歴を示す情報.
type PacketTalkHistory []Talk

// 囁きの履歴を示す情報.
type PacketWhisperHistory []Talk

type Request string

const RequestATTACK Request = "ATTACK"
const RequestDAILYFINISH Request = "DAILY_FINISH"
const RequestDAILYINITIALIZE Request = "DAILY_INITIALIZE"
const RequestDIVINE Request = "DIVINE"
const RequestFINISH Request = "FINISH"
const RequestGUARD Request = "GUARD"
const RequestINITIALIZE Request = "INITIALIZE"
const RequestNAME Request = "NAME"
const RequestTALK Request = "TALK"
const RequestTALKBROADCAST Request = "TALK_BROADCAST"
const RequestTALKPHASEEND Request = "TALK_PHASE_END"
const RequestTALKPHASESTART Request = "TALK_PHASE_START"
const RequestVOTE Request = "VOTE"
const RequestWHISPER Request = "WHISPER"
const RequestWHISPERBROADCAST Request = "WHISPER_BROADCAST"
const RequestWHISPERPHASEEND Request = "WHISPER_PHASE_END"
const RequestWHISPERPHASESTART Request = "WHISPER_PHASE_START"

type Role string

const RoleBODYGUARD Role = "BODYGUARD"
const RoleMEDIUM Role = "MEDIUM"
const RolePOSSESSED Role = "POSSESSED"
const RoleSEER Role = "SEER"
const RoleVILLAGER Role = "VILLAGER"
const RoleWEREWOLF Role = "WEREWOLF"

// ゲームの設定を示す情報の構造体.
type Setting struct {
	// ゲームのプレイヤー数.
	AgentCount int `json:"agent_count"`

	// AttackVote corresponds to the JSON schema field "attack_vote".
	AttackVote SettingAttackVote `json:"attack_vote"`

	// ゲーム内の最大日数. 制限がない場合は None.
	MaxDay *int `json:"max_day,omitempty"`

	// 各役職の人数を示すマップ.
	RoleNumMap map[string]int `json:"role_num_map"`

	// Talk corresponds to the JSON schema field "talk".
	Talk SettingTalk `json:"talk"`

	// Timeout corresponds to the JSON schema field "timeout".
	Timeout SettingTimeout `json:"timeout"`

	// Vote corresponds to the JSON schema field "vote".
	Vote SettingVote `json:"vote"`

	// 投票の結果を公開するか.
	VoteVisibility bool `json:"vote_visibility"`

	// 囁きの設定.
	Whisper SettingTalk `json:"whisper"`
}

// 襲撃投票の設定.
type SettingAttackVote struct {
	// 襲撃なしの日を許可するか.
	AllowNoTarget bool `json:"allow_no_target"`

	// 自己投票を許可するか.
	AllowSelfVote bool `json:"allow_self_vote"`

	// 1位タイの場合の最大襲撃再投票回数.
	MaxCount int `json:"max_count"`
}

// トークの設定.
type SettingTalk struct {
	// グループチャット方式のフェーズ全体の制限時間 (ミリ秒). 設定されていない場合は None.
	Duration *int `json:"duration,omitempty"`

	// MaxCount corresponds to the JSON schema field "max_count".
	MaxCount SettingTalkMaxCount `json:"max_count"`

	// MaxLength corresponds to the JSON schema field "max_length".
	MaxLength SettingTalkMaxLength `json:"max_length"`

	// 1日あたりの1エージェントの最大スキップ回数.
	MaxSkip int `json:"max_skip"`
}

// トークの回数の設定.
type SettingTalkMaxCount struct {
	// 1日あたりの1エージェントの最大発言回数.
	PerAgent int `json:"per_agent"`

	// 1日あたりの全体の発言回数.
	PerDay int `json:"per_day"`
}

// トークの文字数の設定.
type SettingTalkMaxLength struct {
	// 1日あたりの1エージェントの最大文字数に含まない最低文字数. 制限がない場合は None.
	BaseLength *int `json:"base_length,omitempty"`

	// 単語数でカウントするか. 設定されない場合は None.
	CountInWord *bool `json:"count_in_word,omitempty"`

	// 文字数カウントの際に空白を含めてカウントするか. 設定されない場合は None.
	CountSpaces *bool `json:"count_spaces,omitempty"`

	// 1回のトークあたりのメンションを含む場合の追加文字数. 制限がない場合は None.
	MentionLength *int `json:"mention_length,omitempty"`

	// 1日あたりの1エージェントの最大文字数. 制限がない場合は None.
	PerAgent *int `json:"per_agent,omitempty"`

	// 1回のトークあたりの最大文字数. 制限がない場合は None.
	PerTalk *int `json:"per_talk,omitempty"`
}

// タイムアウトの設定.
type SettingTimeout struct {
	// エージェントのアクションのタイムアウト時間 (ミリ秒).
	Action int `json:"action"`

	// エージェントの生存確認のタイムアウト時間 (ミリ秒).
	Response int `json:"response"`
}

// 投票の設定.
type SettingVote struct {
	// 自己投票を許可するか.
	AllowSelfVote bool `json:"allow_self_vote"`

	// 1位タイの場合の最大再投票回数.
	MaxCount int `json:"max_count"`
}

type Species string

const SpeciesHUMAN Species = "HUMAN"
const SpeciesWEREWOLF Species = "WEREWOLF"

type Status string

const StatusALIVE Status = "ALIVE"
const StatusDEAD Status = "DEAD"

// 会話の内容を示す情報の構造体.
type Talk struct {
	// 会話を行ったエージェントの名前.
	Agent string `json:"agent"`

	// 会話が行われた日数.
	Day int `json:"day"`

	// 会話のインデックス.
	Idx int `json:"idx"`

	// 会話がオーバーであるかどうか.
	Over bool `json:"over"`

	// 会話がスキップであるかどうか.
	Skip bool `json:"skip"`

	// 会話の内容.
	Text string `json:"text"`

	// 会話が行われた時刻 (Unixミリ秒).
	Time int `json:"time"`

	// 会話が行われたターン数.
	Turn int `json:"turn"`
}

type Team string

const TeamVILLAGER Team = "VILLAGER"
const TeamWEREWOLF Team = "WEREWOLF"

// 投票の内容を示す情報の構造体.
type Vote struct {
	// 投票を行ったエージェントの名前.
	Agent string `json:"agent"`

	// 投票が行われた日数.
	Day int `json:"day"`

	// 投票の対象となったエージェントの名前.
	Target string `json:"target"`
}
