# 大会向け
# マッチオプティマイザの設定を必要に応じて変更してください

server:
  web_socket:
    host: "127.0.0.1" # ホスト名
    port: 8080 # ポート番号
  authentication:
    enable: False # トークンによる接続認証を有効にするか
    secret: your-256-bit-secret # 秘密鍵

game:
  agent_count: 5 # 1ゲームあたりのエージェント数
  custom_profile:
    enable: False # カスタムプロファイルを有効にするか
    profile:
      Agent01: |-
        Profile01
      Agent02: |-
        Profile02
      Agent03: |-
        Profile03
      Agent04: |-
        Profile04
      Agent05: |-
        Profile05
  vote_visibility: false # 投票の結果を公開するか
  talk_on_first_day: true # 1日目の発言を許可するか
  max_continue_error_ratio: 0.2 # ゲームを継続するエラーエージェントの最大割合
  talk:
    max_count:
      per_agent: 5 # 1日あたりの1エージェントの最大発言回数
      per_day: 20 # 1日あたりの全体の発言回数
    max_length:
      per_talk: -1 # 1回のトークあたりの最大文字数 制限無しの場合は-1
      per_agent: -1 # 1日あたりの1エージェントの最大文字数 制限無しの場合は-1
      base_length: 0 # 1日あたりの1エージェントの最大文字数に含まない最低文字数
      count_in_word: false # 単語数でカウントするか
    max_skip: 0 # 1日あたりの1エージェントの最大スキップ回数
  whisper:
    max_count:
      per_agent: 5 # 1日あたりの1エージェントの最大囁き回数
      per_day: 20 # 1日あたりの全体の囁き回数
    max_length:
      per_talk: -1 # 1回のトークあたりの最大文字数 制限無しの場合は-1
      per_agent: -1 # 1日あたりの1エージェントの最大文字数 制限無しの場合は-1
      base_length: 0 # 1日あたりの1エージェントの最大文字数に含まない最低文字数
      count_in_word: false # 単語数でカウントするか
    max_skip: 0 # 1日あたりの1エージェントの最大スキップ回数
  vote:
    max_count: 1 # 1位タイの場合の最大再投票回数
  attack_vote:
    max_count: 1 # 1位タイの場合の最大襲撃再投票回数
    allow_no_target: false # 襲撃なしの日を許可するか
  timeout:
    action: 60s # エージェントのアクションのタイムアウト時間
    response: 120s # エージェントの生存確認のタイムアウト時間
    acceptable: 5s # サーバ側での猶予時間

json_logger:
  enable: true # JSONログの出力を有効にするか
  output_dir: "./log" # JSONログの出力ディレクトリ
  filename: "{timestamp}_{teams}" # JSONログのファイル名

game_logger:
  enable: true # ゲームログの出力を有効にするか
  output_dir: "./log" # ゲームログの出力ディレクトリ
  filename: "{timestamp}_{teams}" # ゲームログのファイル名

realtime_broadcaster:
  enable: true # リアルタイムログの出力を有効にするか

matching:
  self_match: true # 同じチーム名のエージェント同士のみをマッチングさせるか
  is_optimize: false # 最適化した組み合わせマッチングを有効にするか (self_match が false の場合に限る)
  team_count: 5 # 参加するチーム数
  game_count: 30 # 全体のゲーム数
  output_path: "./log/match_optimizer.json" # マッチ履歴の出力ファイル
  infinite_loop: false # 組み合わせマッチングがすべて終了した場合に全体のゲーム数分のゲームを追加するか
