name: Release
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Build Multi Platform
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=$(git describe --tag --abbrev=0) -X main.revision=$(git rev-list -1 HEAD) -X main.build=$(git describe --tags)" -o dist/aiwolf-nlp-server-linux-amd64
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=$(git describe --tag --abbrev=0) -X main.revision=$(git rev-list -1 HEAD) -X main.build=$(git describe --tags)" -o dist/aiwolf-nlp-server-windows-amd64.exe
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=$(git describe --tag --abbrev=0) -X main.revision=$(git rev-list -1 HEAD) -X main.build=$(git describe --tags)" -o dist/aiwolf-nlp-server-darwin-amd64
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=$(git describe --tag --abbrev=0) -X main.revision=$(git rev-list -1 HEAD) -X main.build=$(git describe --tags)" -o dist/aiwolf-nlp-server-darwin-arm64
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/aiwolf-nlp-server-linux-amd64
            dist/aiwolf-nlp-server-windows-amd64.exe
            dist/aiwolf-nlp-server-darwin-amd64
            dist/aiwolf-nlp-server-darwin-arm64
            config/default.yml
            config/.env.example
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
