name: Test and Upload Results
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -race -ldflags "-X main.version=$(git describe --tag --abbrev=0) -X main.revision=$(git rev-list -1 HEAD) -X main.build=$(git describe --tags)" -v ./...
      - name: Test with the Go CLI
        run: go test -race -ldflags "-X main.version=$(git describe --tag --abbrev=0) -X main.revision=$(git rev-list -1 HEAD) -X main.build=$(git describe --tags)" -v ./...
      - name: Upload JSON Log
        uses: actions/upload-artifact@v4
        with:
          name: json-logger
          path: log/json/*.json
      - name: Upload Game Log
        uses: actions/upload-artifact@v4
        with:
          name: game-logger
          path: log/game/*.log
      - name: Upload Realtime Broadcaster Log
        uses: actions/upload-artifact@v4
        with:
          name: realtime-broadcaster
          path: log/realtime/*.jsonl
